version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: tpi_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todos_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: secure_password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  back:
    build:
      context: ./back
    container_name: tpi_back
    restart: unless-stopped
    environment:
      DATABASE_URL: 'mysql+pymysql://todo_user:secure_password@db:3306/todos_db'
    depends_on:
      - db
    ports:
      - '8000:8000'
    volumes:
      - ./back:/app

  front:
    build:
      context: ./front
    container_name: tpi_front
    restart: unless-stopped
    ports:
      - '8080:80'
    depends_on:
      - back

volumes:
  db_data:
