name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:

env:
  IMAGE_BACK: docker.io/franperrone/tpi-back
  IMAGE_FRONT: docker.io/franperrone/tpi-front


jobs:
  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        run: |
          source venv/bin/activate
          pytest

  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Validar estructura del frontend
        run: |
          echo "Archivos en front/"
          ls -la

# CD:
  docker-publish:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backend image
        run: docker build -t $IMAGE_BACK:latest ./back

      - name: Build frontend image
        run: docker build -t $IMAGE_FRONT:latest ./front

      - name: Push backend image
        run: docker push $IMAGE_BACK:latest

      - name: Push frontend image
        run: docker push $IMAGE_FRONT:latest

  deploy-back:
    needs: [docker-publish]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger backend deploy on Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-d4em2q2li9vc73avh6fg \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"


  deploy-front:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Inyectar URL del backend en index.html
        run: |
          sed -i 's|<!--__API_BASE__-->|<script>window.__API_BASE__="https://tpi-back.onrender.com"</script>|' dist/index.html

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build frontend image
        run: docker build -t $IMAGE_FRONT:latest .

      - name: Push frontend image
        run: docker push $IMAGE_FRONT:latest

      - name: Trigger frontend deploy on Render
        run: |
          curl -X POST https://api.render.com/deploy/srv-d4emknogjchc73fk7kmg \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"